version: "3.8"

services:
  icketi-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always  
    depends_on:
      - postgres
      - redis
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env.${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - myapp-network  
    

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env.${NODE_ENV}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - myapp-network  

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - myapp-network

networks:
  myapp-network:
    external: true

volumes:
  db_data: