version: "3.8"

services:
  icketi-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always  
    depends_on:
      - postgres
      - redis
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env.${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - myapp-network  
    

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env.${NODE_ENV}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - myapp-network  

  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_LOCAL_PORT}:${REDIS_CONTAINER_PORT}"
    env_file:
      - .env.${NODE_ENV}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - myapp-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8085:8081"
    env_file:
      - .env.${NODE_ENV}  
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:${REDIS_CONTAINER_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: root
      HTTP_PASSWORD: root
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
  db_data:
